# Generated by Django 5.2.4 on 2025-07-21 10:20

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('age', models.IntegerField(validators=[hotel.models.ageCriteria])),
                ('mobile', models.CharField(max_length=10, validators=[hotel.models.mobileCriteria])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=6, validators=[hotel.models.passwordCriteria])),
            ],
        ),
    ]
